services:
    db:
        image: mysql
        restart: always
        ports:
            - 3306:3306
        environment:
            #   MYSQL_ROOT_PASSWORD: root
            MYSQL_ALLOW_EMPTY_PASSWORD: "1"
        volumes:
            - sales_inventory_system_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 32512:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=db

volumes:
    sales_inventory_system_data:
